# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\"3\n\nRagRequest\x12\x12\n\nuser_query\x18\x01 \x01(\t\x12\x11\n\tpatent_no\x18\x02 \x01(\t\"\x1d\n\x0bRagResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"&\n\x11PatentInfoRequest\x12\x11\n\tpatent_no\x18\x01 \x01(\t\")\n\x12PatentInfoResponse\x12\x13\n\x0bpatent_info\x18\x01 \x01(\t\".\n\x19\x45nterpriseInterestRequest\x12\x11\n\tpatent_no\x18\x01 \x01(\t\"4\n\x1a\x45nterpriseInterestResponse\x12\x16\n\x0einterest_level\x18\x01 \x01(\t\"\x1d\n\x0c\x41gentRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1f\n\rAgentResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2\xc3\x01\n\nRagService\x12)\n\x0cGetRagAnswer\x12\x0b.RagRequest\x1a\x0c.RagResponse\x12\x38\n\rGetPatentInfo\x12\x12.PatentInfoRequest\x1a\x13.PatentInfoResponse\x12P\n\x15GetEnterpriseInterest\x12\x1a.EnterpriseInterestRequest\x1a\x1b.EnterpriseInterestResponse25\n\x0c\x41gentService\x12%\n\x04\x43hat\x12\r.AgentRequest\x1a\x0e.AgentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAGREQUEST']._serialized_start=13
  _globals['_RAGREQUEST']._serialized_end=64
  _globals['_RAGRESPONSE']._serialized_start=66
  _globals['_RAGRESPONSE']._serialized_end=95
  _globals['_PATENTINFOREQUEST']._serialized_start=97
  _globals['_PATENTINFOREQUEST']._serialized_end=135
  _globals['_PATENTINFORESPONSE']._serialized_start=137
  _globals['_PATENTINFORESPONSE']._serialized_end=178
  _globals['_ENTERPRISEINTERESTREQUEST']._serialized_start=180
  _globals['_ENTERPRISEINTERESTREQUEST']._serialized_end=226
  _globals['_ENTERPRISEINTERESTRESPONSE']._serialized_start=228
  _globals['_ENTERPRISEINTERESTRESPONSE']._serialized_end=280
  _globals['_AGENTREQUEST']._serialized_start=282
  _globals['_AGENTREQUEST']._serialized_end=311
  _globals['_AGENTRESPONSE']._serialized_start=313
  _globals['_AGENTRESPONSE']._serialized_end=344
  _globals['_RAGSERVICE']._serialized_start=347
  _globals['_RAGSERVICE']._serialized_end=542
  _globals['_AGENTSERVICE']._serialized_start=544
  _globals['_AGENTSERVICE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
