# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRagAnswer = channel.unary_unary(
                '/RagService/GetRagAnswer',
                request_serializer=rag__pb2.RagRequest.SerializeToString,
                response_deserializer=rag__pb2.RagResponse.FromString,
                _registered_method=True)
        self.GetPatentInfo = channel.unary_unary(
                '/RagService/GetPatentInfo',
                request_serializer=rag__pb2.PatentInfoRequest.SerializeToString,
                response_deserializer=rag__pb2.PatentInfoResponse.FromString,
                _registered_method=True)
        self.GetEnterpriseInterest = channel.unary_unary(
                '/RagService/GetEnterpriseInterest',
                request_serializer=rag__pb2.EnterpriseInterestRequest.SerializeToString,
                response_deserializer=rag__pb2.EnterpriseInterestResponse.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRagAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatentInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnterpriseInterest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRagAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagAnswer,
                    request_deserializer=rag__pb2.RagRequest.FromString,
                    response_serializer=rag__pb2.RagResponse.SerializeToString,
            ),
            'GetPatentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatentInfo,
                    request_deserializer=rag__pb2.PatentInfoRequest.FromString,
                    response_serializer=rag__pb2.PatentInfoResponse.SerializeToString,
            ),
            'GetEnterpriseInterest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnterpriseInterest,
                    request_deserializer=rag__pb2.EnterpriseInterestRequest.FromString,
                    response_serializer=rag__pb2.EnterpriseInterestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRagAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RagService/GetRagAnswer',
            rag__pb2.RagRequest.SerializeToString,
            rag__pb2.RagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RagService/GetPatentInfo',
            rag__pb2.PatentInfoRequest.SerializeToString,
            rag__pb2.PatentInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnterpriseInterest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RagService/GetEnterpriseInterest',
            rag__pb2.EnterpriseInterestRequest.SerializeToString,
            rag__pb2.EnterpriseInterestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/AgentService/Chat',
                request_serializer=rag__pb2.AgentRequest.SerializeToString,
                response_deserializer=rag__pb2.AgentResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=rag__pb2.AgentRequest.FromString,
                    response_serializer=rag__pb2.AgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AgentService/Chat',
            rag__pb2.AgentRequest.SerializeToString,
            rag__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
